Open store for writing review on iOS
chemerisuk/cordova-plugin-app-review pull request #20
Opened 2022-11-16 08:19 UTC by soerenBoisen

- add: on iOS calling openStoreScreen does not open the write review form as the documentation states that it should; according to Apples documentation a query param must be added to actually open the review

See: https://developer.apple.com/documentation/storekit/requesting_app_store_reviews?language=objc

2022-11-18 10:17 UTC, soerenBoisen commented
@chemerisuk Can you have a quick look at this? It is a pretty small change.

2022-11-23 08:45 UTC, chemerisuk commented
@soerenBoisen the logic is that `openStoreScreen` method is used to open app page in app/play stores. `requestReview` method is used to open dialog that allows to send review.

I don't like that your change because it changes that. Why can't you use `requestReview`?

2022-11-23 09:59 UTC, soerenBoisen commented
@chemerisuk Your documentation says:

> Launches App/Play store page with a review form.

So I assumed that it was supposed to open the store page and show review form. Your Android screenshots seem to indicate that as well? (Didn't try it on Android yet, so don't know how it actually works).

This is what the change does. Without it, `openStoreScreen` will simply open App Store for the app and the user has to scroll down and find the review action.

The reason I want to use `openStoreScreen` in my app, is to provide a permanent shortcut to review the app from the in-app settings. I cannot use `requestReview` for that, since it may or may not open a review dialog depending on, how many times it has been shown to the user already.

Since this action is user-initiated and not a spontaneous popup, it should not be subject to rate-limiting.

I am fine with adding a separate JS function to do it, if you want to preserve current functionality?

Something like `openStoreForReview` maybe?

2022-11-28 09:02 UTC, chemerisuk requested changes
@soerenBoisen Let's add new flag to `openStoreScreen` in order to implement what you want. See my comments below.

2022-11-28 09:02 UTC, chemerisuk commented on www/AppReview.js
>  function(packageName) {
Let's move `writeReview` to be function argument and be falsy by default. This flag will work only for iOS
```suggestion
function(packageName, writeReview) {
```
Also don't forget to update jsdocs comment with param `writeReview` description.

2022-11-28 09:02 UTC, chemerisuk commented on src/ios/AppReviewPlugin.m
> +        NSString* storeReviewURL = [NSString stringWithFormat:@"https://apps.apple.com/app/id%@?action=write-review", trackId];
DRY code
```suggestion
        if (writeReview) {
          storeURL = [NSString stringWithFormat:@"%@?action=write-review", storeURL];
        }
```
So you don't need if statement at line 31

2022-11-29 13:11 UTC, soerenBoisen commented
@chemerisuk Applied suggested changes. Is the JSDoc okay?

2022-11-29 13:23 UTC, merged

2022-11-29 13:23 UTC, chemerisuk commented
@soerenBoisen looks good, thanks!